### ISSUE TITLE
Why do "action" icons have .5rem padding?

### ISSUE THREAD

**Issue by kaelig** [salesforce/design-system-react#94]
In /components/SLDSIcons/Icon

``` scss
    const styles = this.props.category === "action" ? {padding: "0.5rem"}:null;
```
